theme: jekyll-theme-cayman
title: OHDataDownload.documentation
description: OpenHistorian Data Download Panel
github:
  repository_name: Grafana-oh-datadownload
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji